name: Codecov
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Generate coverage report
      run: |
        pip install -r requirements-dev.txt
        coverage run -m pytest
        coverage combine
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        env_vars: OS,PYTHON
        flags: unittests
        name: codecov-umbrella
        verbose: true
